---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-networkobj
  namespace: sdewan-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovn4nfvk8s-cni"
    }'

