apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-07-12T13:13:41Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: echo-bio
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  name: echo-bio
  resourceVersion: "739"
  uid: 4f57309c-b439-4a38-8b86-b11e22c53270
spec:
  podCIDR: 10.233.64.0/24
  podCIDRs:
  - 10.233.64.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
status:
  addresses:
  - address: 10.0.0.216
    type: InternalIP
  - address: echo-bio
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "72710321237"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8039632Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 78895748Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8142032Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2022-07-12T13:17:50Z"
    lastTransitionTime: "2022-07-12T13:13:39Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-07-12T13:17:50Z"
    lastTransitionTime: "2022-07-12T13:13:39Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-07-12T13:17:50Z"
    lastTransitionTime: "2022-07-12T13:13:39Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-07-12T13:17:50Z"
    lastTransitionTime: "2022-07-12T13:13:39Z"
    message: 'container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady
      message:Network plugin returns error: cni plugin not initialized'
    reason: KubeletNotReady
    status: "False"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - k8s.gcr.io/etcd@sha256:13f53ed1d91e2e11aac476ee9a0269fdda6cc4874eba903efd40daf50c55eee5
    - k8s.gcr.io/etcd:3.5.3-0
    sizeBytes: 102143581
  - names:
    - k8s.gcr.io/kube-proxy@sha256:7e75c20c0fb0a334fa364546ece4c11a61a7595ce2e27de265cacb4e7ccc7f9f
    - k8s.gcr.io/kube-proxy:v1.24.2
    sizeBytes: 39515830
  - names:
    - k8s.gcr.io/kube-apiserver@sha256:433696d8a90870c405fc2d42020aff0966fb3f1c59bdd1f5077f41335b327c9a
    - k8s.gcr.io/kube-apiserver:v1.24.2
    sizeBytes: 33795763
  - names:
    - k8s.gcr.io/kube-controller-manager@sha256:d255427f14c9236088c22cd94eb434d7c6a05f615636eac0b9681566cd142753
    - k8s.gcr.io/kube-controller-manager:v1.24.2
    sizeBytes: 31035052
  - names:
    - quay.io/tigera/operator@sha256:478856ec2359008c9df97442dabe1874fd914819e3e242b3371e88f4f99328eb
    - quay.io/tigera/operator:v1.27.7
    sizeBytes: 18112044
  - names:
    - k8s.gcr.io/kube-scheduler@sha256:b5bc69ac1e173a58a2b3af11ba65057ff2b71de25d0f93ab947e16714a896a1f
    - k8s.gcr.io/kube-scheduler:v1.24.2
    sizeBytes: 15488980
  - names:
    - k8s.gcr.io/coredns/coredns@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e
    - k8s.gcr.io/coredns/coredns:v1.8.6
    sizeBytes: 13585107
  - names:
    - k8s.gcr.io/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
    - k8s.gcr.io/pause:3.7
    sizeBytes: 311278
  - names:
    - k8s.gcr.io/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db
    - k8s.gcr.io/pause:3.6
    sizeBytes: 301773
  nodeInfo:
    architecture: amd64
    bootID: d84e703f-fd9f-461c-8bd1-4ebc264c3676
    containerRuntimeVersion: containerd://1.6.6
    kernelVersion: 5.15.0-40-generic
    kubeProxyVersion: v1.24.2
    kubeletVersion: v1.24.2
    machineID: 9bd451a287c14625ac696a3e9448a96b
    operatingSystem: linux
    osImage: Ubuntu 22.04 LTS
    systemUUID: 745f4d56-2973-f3b7-e183-bb3707beab10
